### ISSUE TITLE
Document 'Books'

### ISSUE THREAD

**Issue by nrooney** [w3c-webmob/wake-lock-use-cases#10]
Google Play Books on Android. Screen stays 'awake' allowing users to continue reading.

![2014-06-19 14 22 24](https://cloud.githubusercontent.com/assets/1921478/3328535/a0c79c7e-f7bd-11e3-83a7-c2349bf7e0a3.png)

**Comment by marcoscaceres** [comment]
Closed via 331d38fe4504adae58a56a96e5fc45c5c695d363
