### ISSUE TITLE
Document chat apps

### ISSUE THREAD

**Issue by nrooney** [w3c-webmob/wake-lock-use-cases#12]

**Comment by nrooney** [comment]
![2014-07-09 10 36 41](https://cloud.githubusercontent.com/assets/1921478/3525143/50538aec-0770-11e4-884e-d1e67cb8f4d2.png)

Crappy pic, need a new one

**Comment by marcoscaceres** [comment]
This is similar to the Brazil 2014 use case (stream of textual data). As such, I think we have it covered.
