### ISSUE TITLE
Wake lock is necessary for VR applications

### ISSUE THREAD

**Issue by borismus** [w3c-webmob/wake-lock-use-cases#18]
For example, [Google Cardboard](http://g.co/cardboard) needs to stay awake since there's no direct user interaction with the screen.

See related Chrome bug: http://crbug.com/386255

**Comment by borismus** [comment]
(@marcoscaceres)

**Comment by marcoscaceres** [comment]
thanks @borismus. Will definitely add!

**Comment by marcoscaceres** [comment]
Added to doc under "other applications" section.
