### ISSUE TITLE
Wake locks with limited time

### ISSUE THREAD

**Issue by boiler23** [w3c-webmob/wake-lock-use-cases#19]
@marcoscaceres, what do you think about limited lifetime for wake locks?
This may be very useful for book readers, where you don't need to keep screen awake all the time, but you may need more time to read the page than system gives you. For example, book reader may have options for keeping screen on for 1, 2, 5, 10 minutes.
Maybe we should even reject wake locks with unlimited lifetime for safety purposes - if something goes wrong on the page it would still release the wake lock.

**Comment by marcoscaceres** [comment]
So, we found one app that exhibits this behavior (Android's Books app). However, we haven't _yet_ got any implementer feedback that we should have this as a requirement. I will check with the Moz folks internally about what they think. 

My feeling is that it could be a nice hint for the UA - so lets shop the idea around a bit before we add it as a requirement.
