### ISSUE TITLE
Media Gallery use case

### ISSUE THREAD

**Issue by boiler23** [w3c-webmob/wake-lock-use-cases#23]
I think Media Gallery use case also should be added to the list. Screen wake locks would be useful when viewing photos in slideshow mode. Almost all desktop image viewers handle this case properly.

**Comment by marcoscaceres** [comment]
Hi @boiler23. 

Sure! For the app you had in mind, can you either a send a PR or answer the following (+ include a screenshot):
- Why does the application need a wake lock?
- How does the user benefit?
- When is the wake lock applied and released?

**Comment by boiler23** [comment]
Sure, I'll provide PR!

**Comment by boiler23** [comment]
Added PR #24

**Comment by marcoscaceres** [comment]
(_pro tip:_ Github will automatically close the issue when we merge the PR)
