### ISSUE TITLE
Document XMBC

### ISSUE THREAD

**Issue by domenic** [w3c-webmob/wake-lock-use-cases#3]
https://twitter.com/EINS78/status/479001526233743360

I bet most media gallery apps do the same thing. (Plex, XMBC, Boxee, Windows Media Center, Front Row, ...)

**Comment by marcoscaceres** [comment]
Duplicate of #5

**Comment by marcoscaceres** [comment]
I'm going to add the fullscreen aspect as a requirement. That is, a browser might only support this functionality if the application is running in fullscreen.
