### ISSUE TITLE
Document Google Maps

### ISSUE THREAD

**Issue by domenic** [w3c-webmob/wake-lock-use-cases#4]
https://twitter.com/EichTyler/status/479038406333186048

During turn-by-turn driving directions

**Comment by nrooney** [comment]
Google Maps. When in navigation mode the screen will stay 'awake' so users do not need to wake the screen when (say) driving and using the navigation feature.

![2014-06-19 14 05 40](https://cloud.githubusercontent.com/assets/1921478/3328406/4897df24-f7bc-11e3-854b-66cacb14ee5e.png)

**Comment by marcoscaceres** [comment]
Closed via 331d38fe4504adae58a56a96e5fc45c5c695d363
