### ISSUE TITLE
Document video players

### ISSUE THREAD

**Issue by sethladd** [w3c-webmob/wake-lock-use-cases#5]
apps that play video, like Netflix

**Comment by edent** [comment]
Is this needed? Checking Chrome, Firefox, and Opera on Android - all keep the screen on when a video is being played - whether fullscreen or not.

I suppose the question is - is this only for non-fullscreen videos?  Are there any UA's which don't already override the system screen-wake timeout when playing video?

**Comment by nrooney** [comment]
Crunchyroll. When playing a video the screen will remain 'awake' so users can view the whole video without the screen shutting down.

![2014-06-19 14 02 03](https://cloud.githubusercontent.com/assets/1921478/3328398/383822a6-f7bc-11e3-9c82-49a258dab11b.png)

**Comment by marcoscaceres** [comment]
> I suppose the question is - is this only for non-fullscreen videos? Are there any UA's which don't already override the system screen-wake timeout when playing video?

@edent, so we want to document both. That in cases where an application can put a HTML element full-screen the API is not needed - and absolutely should not be able to override the default behavior. But it could be useful where video is not fullscreen. For example, in a video chat app that has real time text communication but it's not fullscreen.

**Comment by marcoscaceres** [comment]
Closed via 331d38fe4504adae58a56a96e5fc45c5c695d363

I added a mention of this default behavior in the "[Why we need wake locks on the Web](https://w3c-webmob.github.io/wake-lock-use-cases/#why-we-need-wake-locks-on-the-web)" section.
