### ISSUE TITLE
Document table-top "life trackers"

### ISSUE THREAD

**Issue by sethladd** [w3c-webmob/wake-lock-use-cases#6]
For example, https://play.google.com/store/apps/details?id=com.lander.hello

**Comment by nrooney** [comment]
Magic The Gathering Counter stays 'awake' for users to count lives without having the screen dim whilst playing a game of magic the gathering.

![2014-06-19 13 54 21](https://cloud.githubusercontent.com/assets/1921478/3328293/084a6e10-f7bb-11e3-939c-6e73e30ecfa2.png)
