### ISSUE TITLE
Document cooking apps

### ISSUE THREAD

**Issue by sethladd** [w3c-webmob/wake-lock-use-cases#7]
For example, https://play.google.com/store/apps/details?id=com.mufumbo.android.recipe.search

**Comment by sethladd** [comment]
And https://play.google.com/store/apps/details?id=com.scripps.android.foodnetwork

**Comment by marcoscaceres** [comment]
Nigela's app is also a great example: 
https://itunes.apple.com/gb/app/nigellissima/id556890983?ls=1&mt=8

**Comment by marcoscaceres** [comment]
Actually, going to document this one (as it's the one that I have on my phone): 
https://itunes.apple.com/ca/app/nigella-quick-collection/id366478575

**Comment by nrooney** [comment]
All the cooks app. Screen stays 'awake' when users are viewing a recipe so they can cook without touching the buttons / screen to wake.

![2014-06-19 13 55 08](https://cloud.githubusercontent.com/assets/1921478/3328375/eea1ffb8-f7bb-11e3-94fa-288292968744.png)

**Comment by nrooney** [comment]
@sethladd food network app doesn't keep the screen awake on Android (at least for me!) are you using iOS or a different version maybe? Thanks!

**Comment by sethladd** [comment]
I was scanning their permissions, which indicated the app can request to keep the device from sleeping.

Regardless, I think we have enough cooking examples. :)

**Comment by marcoscaceres** [comment]
@sethladd that's also good to know - sorry we missed that! Setting as custom preference is also a good use case as it indicates that this preference might need to be persistent across sessions... or if it can't be, at least we can explore alternative ways of faking this.
