### ISSUE TITLE
Document "Healthcare Applications"

### ISSUE THREAD

**Issue by damondouglas** [w3c-webmob/wake-lock-use-cases#8]
In some healthcare situations, we do continuous cardiac monitoring:  https://play.google.com/store/apps/details?id=com.alivecor.aliveecg

**Comment by marcoscaceres** [comment]
@damondouglas, this is great: 

I'm just going to say. The "AliveECG - Heart Monitor" for Android is an application that records and review single-channel electrocardiogram (ECG) rhythm strips. The screen that shows the beats per minute prevents the screen from locking. This allows patients and medical professionals to monitor the ECG input in real-time without needing to worry that the device will go to sleep.

**Comment by nrooney** [comment]
ECG App. The app will remain awake on the screen that measures a user's BPM.

![screenshot_2014-06-19-22-59-33](https://cloud.githubusercontent.com/assets/1921478/3328429/8d2dfb28-f7bc-11e3-99d4-d50c22132ac4.png)

**Comment by marcoscaceres** [comment]
Added to document in "other applications" section
